### ISSUE TITLE
Widescreen boxing

### ISSUE THREAD

**Issue by FIFARenderZ** [amiroff/NextBook#17]
When having the NextBook page open on a widescreen it currently looks like this:
![image](https://user-images.githubusercontent.com/16150031/114297676-4b1d4e00-9ab2-11eb-91f1-2968e6026c45.png)
The font gets bigger as well which looks a little wierd in my opinion.

Would it be possible to box this in? (Like GitBook for example)
![image](https://user-images.githubusercontent.com/16150031/114297680-52dcf280-9ab2-11eb-919e-59f53f6472a1.png)

**Comment by amiroff** [comment]
Hello, that's definitely possible, but need some modifications to codebase because the css framework I am using has strict rules related to sidebar positioning. I got prototype working but needs mobile support too. 
[Screenshot](https://www.dropbox.com/s/k9t31am9atglt2n/screen.png?dl=0)

**Comment by amiroff** [comment]
OK, 
@FIFARenderZ 
Solution to first part related font autoscaling is already in master, just create a new app and change `fontAutoScaling` to `false`. 

Container part will come soon I hope.

**Comment by FIFARenderZ** [comment]
Awesome! Thanks for the quick resolution 😄

**Comment by amiroff** [comment]
@FIFARenderZ fixed with #18 , centered layout is now default, thanks for suggestion.

Please create a new project and let me know how it goes.

**Comment by FIFARenderZ** [comment]
Looks much better now, thanks!
![image](https://user-images.githubusercontent.com/16150031/114677722-de50c080-9d0a-11eb-8287-cac723b2b8b5.png)

**Comment by amiroff** [comment]
> Looks much better now, thanks!
> ![image](https://user-images.githubusercontent.com/16150031/114677722-de50c080-9d0a-11eb-8287-cac723b2b8b5.png)

Ouch! What resolution is that? :)

**Comment by FIFARenderZ** [comment]
> Ouch! What resolution is that? :)
This is 3440x1440. It looks good tho!
