### ISSUE TITLE
What's the bare minimum command to run to get static content ?

### ISSUE THREAD

**Issue by johnchristopher** [amiroff/NextBook#21]
Hello,

I am a bit confused. I can run `npm run dev:watch` and get something on http://localhost:3000 but how do I export this to static pages ?

So I could just copy those pages to apache, nginx, S3, etc. ? 

`npm run build` seems to build something but the current folder don't have any new files or directory. `npm run export` complains about page "/" and says to consult next.js help.

Thanks :).

**Comment by amiroff** [comment]
Hey!

Thanks for the question, and it's a very valid one. I just pushed a small update in code and docs to eanble hosting on static platforms (with no node.js support) out of the box. So you should create a new project, `npm install`, and when your content is ready `npm run export`. This will create a `out` directory which you can just deploy on any hosting platform or just serve with any web server. I would still recommend using Vercel though, too easy not to use :)

**Comment by johnchristopher** [comment]
Thanks :).
